### ISSUE TITLE
Gracefully fallback for bit libraries

### ISSUE THREAD

**Issue by daurnimator** [keplerproject/luarocks#320]
How can I gracefully fallback with bit libraries and luarocks?

I wrote some code that works with lua 5.3 *or* luabitop.
But luabitop won't compile with lua 5.3.
So it looks like I can't support all lua versions with the one rockspec?

(output from https://travis-ci.org/daurnimator/lua-http/jobs/54412346#L523 )
> Using https://rocks.moonscript.org/luabitop-1.0.2-1.src.rock... switching to 'build' mode
> gcc -O2 -fPIC -I/usr/local/include -c bit.c -o bit.o
> bit.c: In function ‘barg’:
> bit.c:83:2: error: #error "Unknown number type, check LUA_NUMBER_* in luaconf.h"
> Error: Failed installing dependency: https://rocks.moonscript.org/luabitop-1.0.2-1.src.rock - Build error: Failed compiling object bit.o

**Comment by siffiejoe** [comment]
Use two different rockspecs (one for Lua 5.3 *without* luabitop in the dependencies, and one for Lua 5.1/5.2 *with* luabitop), or use bit32 instead of luabitop. bit32 is available for Lua 5.1, 5.2, and 5.3.

**Comment by daurnimator** [comment]
> looks like I can't support all lua versions with the one rockspec?



> Use two different rockspecs (one for Lua 5.3 without luabitop in the dependencies, and one for Lua 5.1/5.2 with luabitop)

So: yep :p




> use bit32 instead of luabitop. bit32 is available for Lua 5.1, 5.2, and 5.3.

ah ha! this might save me for now.
